config/routes.rb
Rails.application.routes.draw do

  root "bus_prediction#index"

  post "bus_prediction_from_postcode", to: "bus_prediction#bus_prediction_from_postcode"
end

app/models/address.rb
class Address < ApplicationRecord
  include WebRequestHelper
  def initialize(postcode)
    @postcode = postcode
    @longitude = nil
    @latitude = nil
    @stop_types_str = nil
    @stop_id_list = []
  end
  def get_location

    web_address = "https://api.postcodes.io/postcodes/#{@postcode}"
    json_file = web_request(web_address)

    if json_file["status"] == 200 && json_file["result"]
      longitude = json_file["result"]["longitude"]
      latitude = json_file["result"]["latitude"]

      if longitude.nil? || latitude.nil?
        raise "Invalid location data. Longitude or latitude is nil."
      else
        [longitude, latitude]
      end
    else
      raise "Invalid postcode. Please enter a valid UK postcode."
    end
  rescue => e
    Rails.logger.error "Error fetching location data: #{e.message}"
    raise e.message
  end

  def get_stop_types
    web_address = 'https://api.tfl.gov.uk/StopPoint/Meta/StopTypes'
    stop_types = web_request(web_address)
    stop_types.join(',')
  rescue => e
    Rails.logger.error "Error fetching stop types: #{e.message}"
    raise e.message
  end

  def get_nearest_stops
    @stop_types_str ||= get_stop_types
    if @longitude.nil? || @latitude.nil?
      @longitude, @latitude = get_location
    end

    stop_id_dict = {}

    web_address = "https://api.tfl.gov.uk/StopPoint?stopTypes=#{@stop_types_str}&lat=#{@latitude}&lon=#{@longitude}"
    stops_info = web_request(web_address)

    stop_points_sorted = stops_info["stopPoints"].sort_by { |stop| stop["distance"] }
    stop_points_nearest= stop_points_sorted.first(1)

    stop_points_nearest.each do |stop_point|
      stop_point['children'].each do |child|
        stop_id_dict[child['id']] = child['commonName']
      end
    end
    stop_id_dict
  rescue => e
    Rails.logger.error "Error fetching nearest stops: #{e.message}"
    raise e.message

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bus_stop.rb
class BusStop < ApplicationRecord
  include WebRequestHelper

  attr_accessor :stop_id, :buses_info

  def initialize(stop_id)
    @stop_id = stop_id
    @buses_info_sorted = nil
  end

  def fetch_buses_info
    web_address = "https://api.tfl.gov.uk/StopPoint/#{@stop_id}/Arrivals"
    buses_info = web_request(web_address)
    buses_info.sort_by { |bus| bus["timeToStation"] }
  rescue => e
    Rails.logger.error "Error fetching buses information: #{e.message}"
    raise e.message
  end

  def bus_prediction(number_of_buses)
    @buses_info_sorted = fetch_buses_info
    if @buses_info_sorted.empty?
      return 'No buses arriving at this stop.'
    end

    next_buses = @buses_info_sorted.first(number_of_buses)

    next_buses.each do |bus|
      result = "Route: #{bus['lineId']}, Destination: #{bus['destinationName']}, Arrives in: #{bus['timeToStation']/60} minutes"
      return result
    end

  rescue => e
    Rails.logger.error "Error making bus predictions: #{e.message}"
    raise e.message
  end
end

app/models/concerns/web_request.rb
require 'net/http'
require 'uri'
require 'json'
module WebRequest
  def web_request(web_address)

    uri = URI(web_address)

    response = Net::HTTP.get_response(uri)

    JSON.parse(response.body)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bus_prediction_controller.rb
class BusPredictionController < ApplicationController
  before_action :validate_postcode, only: [:bus_prediction_from_postcode]
  def index
    @results
  end

  def bus_prediction_from_postcode
    postcode = params[:postcode]

    begin
      address = Address.new(postcode)
      stop_id_dict = address.get_nearest_stops

      if stop_id_dict.empty?
        flash.now[:alert] = "There are no available bus stops near this postcode."
      else
        @results = stop_id_dict.keys.map do |stop_id|
          stop_instance = BusStop.new(stop_id)
          "StopName: "+ stop_id_dict[stop_id] + " | " + stop_instance.bus_prediction(1)
        end

        if @results.empty?
          flash.now[:alert] = "There are no available buses near this postcode."
        end
      end

    rescue => e
      flash.now[:alert] = e.message
    end
    render :index
  end

  private

  def validate_postcode
    postcode = params[:postcode]
    unless postcode.match?(/\A[A-Z]{1,2}\d[A-Z\d]?\d[A-Z]{2}\z/i)
      flash.now[:alert] = "Invalid postcode format. Please enter a valid UK postcode (e.g., NW51TL)."
      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bus_prediction_helper.rb
module BusPredictionHelper
end

app/helpers/web_request_helper.rb
require 'net/http'
require 'uri'
require 'json'
module WebRequestHelper
  def web_request(web_address)

    uri = URI(web_address)

    response = Net::HTTP.get_response(uri)

    JSON.parse(response.body)

  end
end

app/views/bus_prediction/index.html.erb
<div class="mx-auto p-2" style="width: 200px;">
  <h1>BusBoard</h1>
</div>

<div id="postcodeHelpBlock" class="form-text mx-auto p-2" style="max-width: 800px; margin: auto;">
  This webpage allows you to find the next buses at the two bus stops nearest to the postcode you have entered.
</div>

<%= form_with url: bus_prediction_from_postcode_path, local: true, data: { turbo: false } do %>
  <div class="mb-3 mt-4" style="max-width: 500px; margin: auto;">
    <%= label_tag :postcode, "Postcode", class: "form-label" %>
    <div class="d-flex">
      <%= text_field_tag :postcode, nil, class: "form-control me-2", id: "inputPostcode", aria: { describedby: "postcodeHelpBlock" } %>
      <%= submit_tag "Get BusBoard", class: "btn btn-primary" %>
    </div>
  </div>
  <div id="postcodeHelpBlock" class="form-text" style="max-width: 500px; margin: auto;">
    Please enter a valid postcode as a combination of capital letters and numbers without any spaces. (e.g. NW51TL)
  </div>
<% end %>

<div id="result" class="card mx-auto mt-4 p-2" style="width: 800px;">
  <div class="card-body">
    <h5 class="card-title">Bus Board</h5>
    <p class="card-text">This board displays the buses due to arrive in the nearest two stops.</p>
  </div>
  <% if @results.present? %>
    <ul class="list-group list-group-flush">
      <% @results.each do |result| %>
        <li class="list-group-item"><%= result %></li>
      <% end %>
    </ul>
  <% end %>
</div>




app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BusBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            const form = document.querySelector('form');
            form.addEventListener('ajax:success', () => {
                form.reset();
            });

        });
    </script>
  </head>

  <body>
    <div class="container mt-4">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type == 'alert' ? 'danger' : type %>" role="alert">
          <%= message %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>